# Generated by Django 3.2.9 on 2021-11-01 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mpiapi0', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['creation_date']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['creation_date']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='owner',
            new_name='author_name',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='owner',
            new_name='author_name',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created',
            new_name='creation_date',
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Upvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvoted_on', models.DateTimeField(auto_now_add=True)),
                ('author_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpiapi0.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='upvotes_amount',
            field=models.ManyToManyField(blank=True, through='mpiapi0.Upvote', to=settings.AUTH_USER_MODEL),
        ),
    ]
