# Generated by Django 3.2.9 on 2021-11-01 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mpiapi0', '0003_auto_20211101_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upvote',
            name='author_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
